### ISSUE TITLE
Change number of elements per section?

### ISSUE THREAD

**Issue by Curnelius** [woocommerce/homepage-control#27]
I would like to show ALL of my favorite products ( featured), it only show 4, I couldn't find how to change that .

**Comment by jeffikus** [comment]
hi there, can you give me the context please? What theme are you using with this, perhaps could you upload a screenshot so I can better understand the issue?

**Comment by umarmanna** [comment]
I would like to show ALL of my favorite products ( featured), it only show 3, I couldn't find how to change that . its shows only 3 in a row I am using Storefront theme for wordpress

**Comment by jeffikus** [comment]
This sounds like a limitation of the theme. Homepage Control just reorders elements on the page, it doesn't handle how many products are output.
