### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by mahdiyazdani** [woocommerce/homepage-control#29]
Getting the following error(s) with WordPress debug mode ON.

Pure WordPress and Storefront installation along with Homepage control plugin.

![](https://i.gyazo.com/b5b23b9969961dc94ed0556d08349374.png)

**Comment by danieldudzic** [comment]
Hey @mahdiyazdani !

I am struggling to reproduce the issue on my test site.

I am running WordPress with only Storefront and Homepage Control active. `WP_DEBUG` enabled.

Tested with PHP 5.6.20 and 7.1.7 and still no warnings.

From the screenshot, I see that you are using MAMP. Would you mind sharing the environment details (PHP version etc.)?

Thanks!

**Comment by mahdiyazdani** [comment]
@danieldanilov 

Sure, happy to help.

MAMP Version: 4.4
Server API: Apache 2.0 Handler
PHP Version: 7.2.1
WordPress: 4.9.4
Storefront: 2.2.7

**Comment by danieldudzic** [comment]
Thanks @mahdiyazdani !

Ok, I was now able to replicate.

This error seems to be related to a 7.2.0 `count()` behavior change: https://wiki.php.net/rfc/counting_non_countables

This is the line that triggers the warning: https://github.com/woocommerce/homepage-control/blob/master/classes/class-homepage-control-customizer.php#L98

`count( $wp_filter[Homepage_Control()->hook]` to be more specific.
 
I've read multiple threads (including some WP core trac tickets) referencing this issue, but wasn't able to find a solution.

Would you mind taking a look at this, @jeffikus ?

**Comment by mahdiyazdani** [comment]
@danieldanilov 

I am clueless either and thought you guys might have a solution to prevent this from happening.

**Comment by jeffikus** [comment]
Interesting, @danieldudzic I will read up further on this. There are some performance implications of a solution I looked at so I'm hesitant to use it. Also, switching to sizeof() would be futile as it's an alias of count().

Will reply here ASAP.
